# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: wellstsai.Yobi
PackageVersion: 1.8.0
InstallerType: zip
NestedInstallerType: nullsoft
NestedInstallerFiles:
- RelativeFilePath: Yobi-1.8.0-win-x64-Setup.exe
Scope: user
UpgradeBehavior: install
ProductCode: 9e38ce57-3d1f-51c7-ad5f-ca8ddd88900e
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/WellWells/yobi/releases/download/v1.8.0/Yobi-1.8.0-win-x64-Setup.zip
  InstallerSha256: D4830351A61F6F68C4F8BC982F49CF4BC66F7597240370541044C081700F08CC
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-09
